export const offerings = [
  {
    id: "1",
    name: "PixelForge",
    title: "Web Development Experts",
    category: "web",
    city: "bangalore",
    price: 15000,
    rating: 4.8,
    experience: "senior",
    reliabilityScore: 92,
    lat: 12.9716,
    lng: 77.5946,
  },
  {
    id: "2",
    name: "UIHive",
    title: "UI/UX Designers",
    category: "design",
    city: "bangalore",
    price: 8000,
    rating: 4.5,
    experience: "mid",
    reliabilityScore: 84,
    lat: 12.9611,
    lng: 77.6387,
  },
  {
    id: "3",
    name: "CodeNest",
    title: "Full Stack Developers",
    category: "web",
    city: "bangalore",
    price: 20000,
    rating: 4.7,
    experience: "senior",
    reliabilityScore: 89,
    lat: 12.9352,
    lng: 77.6245,
  },
  {
    id: "4",
    name: "AppOrbit",
    title: "Mobile App Developers",
    category: "app",
    city: "bangalore",
    price: 28000,
    rating: 4.6,
    experience: "senior",
    reliabilityScore: 88,
    lat: 12.9822,
    lng: 77.64,
  },
  {
    id: "5",
    name: "LaunchStack",
    title: "Startup MVP Builders",
    category: "web",
    city: "bangalore",
    price: 35000,
    rating: 4.9,
    experience: "senior",
    reliabilityScore: 95,
    lat: 12.9279,
    lng: 77.6271,
  },
  {
    id: "6",
    name: "DesignMint",
    title: "Product UI/UX Designers",
    category: "design",
    city: "chennai",
    price: 10000,
    rating: 4.3,
    experience: "mid",
    reliabilityScore: 80,
    lat: 13.0827,
    lng: 80.2707,
  },
  {
    id: "7",
    name: "AlgoWorks",
    title: "AI/ML Engineers",
    category: "ai",
    city: "chennai",
    price: 25000,
    rating: 4.8,
    experience: "senior",
    reliabilityScore: 91,
    lat: 13.0674,
    lng: 80.2376,
  },
  {
    id: "8",
    name: "DataNova",
    title: "Data Science Experts",
    category: "ai",
    city: "chennai",
    price: 22000,
    rating: 4.6,
    experience: "mid",
    reliabilityScore: 86,
    lat: 13.04,
    lng: 80.21,
  },
  {
    id: "9",
    name: "CloudBridge",
    title: "AWS & DevOps Specialists",
    category: "devops",
    city: "chennai",
    price: 30000,
    rating: 4.7,
    experience: "senior",
    reliabilityScore: 90,
    lat: 13.09,
    lng: 80.28,
  },
  {
    id: "10",
    name: "QuickCode",
    title: "Freelance React Developers",
    category: "web",
    city: "chennai",
    price: 12000,
    rating: 4.4,
    experience: "mid",
    reliabilityScore: 78,
    lat: 13.06,
    lng: 80.25,
  },
  {
    id: "11",
    name: "ByteCraft",
    title: "Backend API Developers",
    category: "backend",
    city: "hyderabad",
    price: 18000,
    rating: 4.5,
    experience: "mid",
    reliabilityScore: 85,
    lat: 17.385,
    lng: 78.4867,
  },
  {
    id: "12",
    name: "UXPulse",
    title: "UX Research Specialists",
    category: "design",
    city: "hyderabad",
    price: 9000,
    rating: 4.2,
    experience: "mid",
    reliabilityScore: 76,
    lat: 17.4,
    lng: 78.48,
  },
  {
    id: "13",
    name: "DevSprint",
    title: "Full Stack Startup Teams",
    category: "web",
    city: "hyderabad",
    price: 40000,
    rating: 4.9,
    experience: "senior",
    reliabilityScore: 94,
    lat: 17.37,
    lng: 78.5,
  },
  {
    id: "14",
    name: "PixelWave",
    title: "Creative Web Designers",
    category: "design",
    city: "hyderabad",
    price: 11000,
    rating: 4.3,
    experience: "mid",
    reliabilityScore: 81,
    lat: 17.36,
    lng: 78.47,
  },
  {
    id: "15",
    name: "AIVerse",
    title: "AI Solutions & Automation",
    category: "ai",
    city: "delhi",
    price: 50000,
    rating: 5.0,
    experience: "senior",
    reliabilityScore: 97,
    lat: 28.6139,
    lng: 77.209,
  },
  {
    id: "16",
    name: "GrowthHackers",
    title: "Digital Marketing Experts",
    category: "marketing",
    city: "delhi",
    price: 7000,
    rating: 4.1,
    experience: "mid",
    reliabilityScore: 74,
    lat: 28.63,
    lng: 77.22,
  },
  {
    id: "17",
    name: "AppForge",
    title: "Flutter App Developers",
    category: "app",
    city: "delhi",
    price: 18000,
    rating: 4.6,
    experience: "mid",
    reliabilityScore: 87,
    lat: 28.62,
    lng: 77.2,
  },
  {
    id: "18",
    name: "StackFusion",
    title: "MERN Stack Experts",
    category: "web",
    city: "delhi",
    price: 22000,
    rating: 4.7,
    experience: "senior",
    reliabilityScore: 90,
    lat: 28.6,
    lng: 77.23,
  },
  {
    id: "19",
    name: "DesignHive",
    title: "Branding & UI Designers",
    category: "design",
    city: "mumbai",
    price: 14000,
    rating: 4.5,
    experience: "mid",
    reliabilityScore: 83,
    lat: 19.076,
    lng: 72.8777,
  },
  {
    id: "20",
    name: "CodeCrafters",
    title: "Startup Tech Teams",
    category: "web",
    city: "mumbai",
    price: 45000,
    rating: 4.8,
    experience: "senior",
    reliabilityScore: 93,
    lat: 19.09,
    lng: 72.86,
  },
  {
    id: "21",
    name: "DevFlow",
    title: "Node.js Backend Experts",
    category: "backend",
    city: "mumbai",
    price: 16000,
    rating: 4.4,
    experience: "mid",
    reliabilityScore: 82,
    lat: 19.1,
    lng: 72.88,
  },
  {
    id: "22",
    name: "PixelGenius",
    title: "Frontend UI Developers",
    category: "web",
    city: "mumbai",
    price: 13000,
    rating: 4.3,
    experience: "junior",
    reliabilityScore: 79,
    lat: 19.07,
    lng: 72.85,
  },
];