-- Seed Professional Roles

INSERT INTO professional_roles (name, normalized_name, category, confidence_level, source, is_verified) VALUES
('Frontend Developer', 'frontenddeveloper', 'engineering', 'high', 'seed', true),
('Backend Developer', 'backenddeveloper', 'engineering', 'high', 'seed', true),
('Full Stack Developer', 'fullstackdeveloper', 'engineering', 'high', 'seed', true),
('DevOps Engineer', 'devopsengineer', 'engineering', 'high', 'seed', true),
('Mobile Developer', 'mobiledeveloper', 'engineering', 'high', 'seed', true),
('Data Scientist', 'datascientist', 'engineering', 'high', 'seed', true),
('Product Manager', 'productmanager', 'product', 'high', 'seed', true),
('Project Manager', 'projectmanager', 'product', 'high', 'seed', true),
('UI/UX Designer', 'uiuxdesigner', 'design', 'high', 'seed', true),
('Product Designer', 'productdesigner', 'design', 'high', 'seed', true),
('Graphic Designer', 'graphicdesigner', 'design', 'high', 'seed', true),
('Marketing Manager', 'marketingmanager', 'marketing', 'high', 'seed', true),
('Sales Representative', 'salesrepresentative', 'sales', 'high', 'seed', true),
('Account Executive', 'accountexecutive', 'sales', 'high', 'seed', true),
('Business Analyst', 'businessanalyst', 'product', 'high', 'seed', true),
('QA Engineer', 'qaengineer', 'engineering', 'high', 'seed', true),
('System Administrator', 'systemadministrator', 'operations', 'high', 'seed', true),
('Network Engineer', 'networkengineer', 'engineering', 'high', 'seed', true),
('Security Engineer', 'securityengineer', 'engineering', 'high', 'seed', true),
('Data Engineer', 'dataengineer', 'engineering', 'high', 'seed', true),
('Machine Learning Engineer', 'machinelearningengineer', 'engineering', 'high', 'seed', true),
('Blockchain Developer', 'blockchaindeveloper', 'engineering', 'high', 'seed', true),
('Game Developer', 'gamedeveloper', 'engineering', 'high', 'seed', true),
('Embedded Systems Engineer', 'embeddedsystemsengineer', 'engineering', 'high', 'seed', true),
('Site Reliability Engineer', 'sitereliabilityengineer', 'engineering', 'high', 'seed', true),
('Scrum Master', 'scrummaster', 'product', 'high', 'seed', true),
('Product Owner', 'productowner', 'product', 'high', 'seed', true),
('Content Strategist', 'contentstrategist', 'marketing', 'high', 'seed', true),
('SEO Specialist', 'seospecialist', 'marketing', 'high', 'seed', true),
('Social Media Manager', 'socialmediamanager', 'marketing', 'high', 'seed', true),
('Growth Hacker', 'growthhacker', 'marketing', 'high', 'seed', true),
('Sales Manager', 'salesmanager', 'sales', 'high', 'seed', true),
('Business Development Manager', 'businessdevelopmentmanager', 'sales', 'high', 'seed', true),
('Financial Analyst', 'financialanalyst', 'finance', 'high', 'seed', true),
('Accountant', 'accountant', 'finance', 'high', 'seed', true),
('Investment Banker', 'investmentbanker', 'finance', 'high', 'seed', true),
('Chief Financial Officer', 'chieffinancialofficer', 'finance', 'high', 'seed', true),
('Operations Manager', 'operationsmanager', 'operations', 'high', 'seed', true),
('Supply Chain Manager', 'supplychainmanager', 'operations', 'high', 'seed', true),
('HR Manager', 'hrmanager', 'hr', 'high', 'seed', true),
('Recruiter', 'recruiter', 'hr', 'high', 'seed', true),
('Talent Acquisition Specialist', 'talentacquisitionspecialist', 'hr', 'high', 'seed', true),
('Legal Counsel', 'legalcounsel', 'legal', 'high', 'seed', true),
('Chief Executive Officer', 'chiefexecutiveofficer', 'executive', 'high', 'seed', true),
('Chief Technology Officer', 'chieftechnologyofficer', 'executive', 'high', 'seed', true),
('Chief Operating Officer', 'chiefoperatingofficer', 'executive', 'high', 'seed', true),
('Founder', 'founder', 'executive', 'high', 'seed', true)
ON CONFLICT (normalized_name) DO NOTHING;

-- Seed Domains

INSERT INTO domains (name, normalized_name, category, confidence_level, source, is_verified) VALUES
('FinTech', 'fintech', 'sector', 'high', 'seed', true),
('HealthTech', 'healthtech', 'sector', 'high', 'seed', true),
('EdTech', 'edtech', 'sector', 'high', 'seed', true),
('E-commerce', 'ecommerce', 'sector', 'high', 'seed', true),
('SaaS', 'saas', 'sector', 'high', 'seed', true),
('Cybersecurity', 'cybersecurity', 'sector', 'high', 'seed', true),
('Blockchain & Web3', 'blockchainweb3', 'sector', 'high', 'seed', true),
('Artificial Intelligence', 'artificialintelligence', 'sector', 'high', 'seed', true),
('IoT', 'iot', 'sector', 'high', 'seed', true),
('Robotics', 'robotics', 'sector', 'high', 'seed', true),
('Biotech', 'biotech', 'sector', 'high', 'seed', true),
('CleanTech', 'cleantech', 'sector', 'high', 'seed', true),
('AgriTech', 'agritech', 'sector', 'high', 'seed', true),
('AdTech', 'adtech', 'sector', 'high', 'seed', true),
('Gaming', 'gaming', 'sector', 'high', 'seed', true),
('Media & Entertainment', 'mediaentertainment', 'sector', 'high', 'seed', true),
('Real Estate', 'realestate', 'sector', 'high', 'seed', true),
('Logistics & Supply Chain', 'logisticssupplychain', 'sector', 'high', 'seed', true),
('Automotive', 'automotive', 'sector', 'high', 'seed', true),
('Aerospace', 'aerospace', 'sector', 'high', 'seed', true),
('Energy', 'energy', 'sector', 'high', 'seed', true),
('Oil & Gas', 'oilgas', 'sector', 'high', 'seed', true),
('Telecommunications', 'telecommunications', 'sector', 'high', 'seed', true),
('Travel & Hospitality', 'travelhospitality', 'sector', 'high', 'seed', true),
('LegalTech', 'legaltech', 'sector', 'high', 'seed', true),
('InsurTech', 'insurtech', 'sector', 'high', 'seed', true),
('PropTech', 'proptech', 'sector', 'high', 'seed', true),
('GovTech', 'govtech', 'sector', 'high', 'seed', true),
('Non-profit', 'nonprofit', 'sector', 'high', 'seed', true),
('Consulting', 'consulting', 'sector', 'high', 'seed', true),
('Web Development', 'webdevelopment', 'topic', 'high', 'seed', true),
('Mobile App Development', 'mobileappdevelopment', 'topic', 'high', 'seed', true),
('Data Analysis', 'dataanalysis', 'topic', 'high', 'seed', true),
('Cloud Computing', 'cloudcomputing', 'topic', 'high', 'seed', true),
('Digital Marketing', 'digitalmarketing', 'topic', 'high', 'seed', true)
ON CONFLICT (normalized_name) DO NOTHING;
