export const offerings = [
  {
    id: "1",
    name: "PixelForge",
    title: "Web Development Experts",
    category: "web",
    city: "bangalore",
    price: 15000,
    rating: 4.8,
    experience: "senior",
    reliabilityScore: 92,
    lat: 12.9716,
    lng: 77.5946,
  },
  {
    id: "2",
    name: "PixelForge",
    title: "React Frontend Developers",
    category: "web",
    city: "bangalore",
    price: 14000,
    rating: 4.7,
    experience: "mid",
    reliabilityScore: 90,
    lat: 12.9732,
    lng: 77.5968,
  },
  {
    id: "3",
    name: "UIHive",
    title: "UI/UX Designers",
    category: "design",
    city: "bangalore",
    price: 8000,
    rating: 4.5,
    experience: "mid",
    reliabilityScore: 84,
    lat: 12.9611,
    lng: 77.6387,
  },
  {
    id: "4",
    name: "UIHive",
    title: "Brand Identity Designers",
    category: "design",
    city: "bangalore",
    price: 9500,
    rating: 4.4,
    experience: "mid",
    reliabilityScore: 82,
    lat: 12.9598,
    lng: 77.6362,
  },
  {
    id: "5",
    name: "CodeNest",
    title: "Full Stack Developers",
    category: "web",
    city: "bangalore",
    price: 20000,
    rating: 4.7,
    experience: "senior",
    reliabilityScore: 89,
    lat: 12.9352,
    lng: 77.6245,
  },
  {
    id: "6",
    name: "CodeNest",
    title: "Backend API Specialists",
    category: "backend",
    city: "bangalore",
    price: 18500,
    rating: 4.6,
    experience: "senior",
    reliabilityScore: 88,
    lat: 12.9344,
    lng: 77.626,
  },
  {
    id: "7",
    name: "AppOrbit",
    title: "Mobile App Developers",
    category: "app",
    city: "bangalore",
    price: 28000,
    rating: 4.6,
    experience: "senior",
    reliabilityScore: 88,
    lat: 12.9822,
    lng: 77.64,
  },
  {
    id: "8",
    name: "AppOrbit",
    title: "Flutter App Developers",
    category: "app",
    city: "bangalore",
    price: 24000,
    rating: 4.7,
    experience: "senior",
    reliabilityScore: 89,
    lat: 12.9801,
    lng: 77.6418,
  },
  {
    id: "9",
    name: "LaunchStack",
    title: "Startup MVP Builders",
    category: "web",
    city: "bangalore",
    price: 35000,
    rating: 4.9,
    experience: "senior",
    reliabilityScore: 95,
    lat: 12.9279,
    lng: 77.6271,
  },
  {
    id: "10",
    name: "LaunchStack",
    title: "Product Strategy for Startups",
    category: "marketing",
    city: "bangalore",
    price: 18000,
    rating: 4.6,
    experience: "senior",
    reliabilityScore: 90,
    lat: 12.9294,
    lng: 77.6258,
  },
  {
    id: "11",
    name: "DesignMint",
    title: "Product UI/UX Designers",
    category: "design",
    city: "chennai",
    price: 10000,
    rating: 4.3,
    experience: "mid",
    reliabilityScore: 80,
    lat: 13.0827,
    lng: 80.2707,
  },
  {
    id: "12",
    name: "DesignMint",
    title: "Landing Page Designers",
    category: "design",
    city: "chennai",
    price: 8500,
    rating: 4.2,
    experience: "mid",
    reliabilityScore: 79,
    lat: 13.0811,
    lng: 80.2683,
  },
  {
    id: "13",
    name: "AlgoWorks",
    title: "AI/ML Engineers",
    category: "ai",
    city: "chennai",
    price: 25000,
    rating: 4.8,
    experience: "senior",
    reliabilityScore: 91,
    lat: 13.0674,
    lng: 80.2376,
  },
  {
    id: "14",
    name: "AlgoWorks",
    title: "AI Automation Specialists",
    category: "ai",
    city: "chennai",
    price: 27000,
    rating: 4.8,
    experience: "senior",
    reliabilityScore: 92,
    lat: 13.0658,
    lng: 80.2362,
  },
  {
    id: "15",
    name: "DataNova",
    title: "Data Science Experts",
    category: "ai",
    city: "chennai",
    price: 22000,
    rating: 4.6,
    experience: "mid",
    reliabilityScore: 86,
    lat: 13.04,
    lng: 80.21,
  },
  {
    id: "16",
    name: "CloudBridge",
    title: "AWS & DevOps Specialists",
    category: "devops",
    city: "chennai",
    price: 30000,
    rating: 4.7,
    experience: "senior",
    reliabilityScore: 90,
    lat: 13.09,
    lng: 80.28,
  },
  {
    id: "17",
    name: "CloudBridge",
    title: "Cloud Infrastructure Setup",
    category: "devops",
    city: "chennai",
    price: 32000,
    rating: 4.8,
    experience: "senior",
    reliabilityScore: 91,
    lat: 13.0881,
    lng: 80.2792,
  },
  {
    id: "18",
    name: "QuickCode",
    title: "Freelance React Developers",
    category: "web",
    city: "chennai",
    price: 12000,
    rating: 4.4,
    experience: "mid",
    reliabilityScore: 78,
    lat: 13.06,
    lng: 80.25,
  },
  {
    id: "19",
    name: "QuickCode",
    title: "Startup Website Builders",
    category: "web",
    city: "chennai",
    price: 13500,
    rating: 4.5,
    experience: "mid",
    reliabilityScore: 80,
    lat: 13.0587,
    lng: 80.2481,
  },
  {
    id: "20",
    name: "ByteCraft",
    title: "Backend API Developers",
    category: "backend",
    city: "hyderabad",
    price: 18000,
    rating: 4.5,
    experience: "mid",
    reliabilityScore: 85,
    lat: 17.385,
    lng: 78.4867,
  },
  {
    id: "21",
    name: "ByteCraft",
    title: "Node.js Microservices Experts",
    category: "backend",
    city: "hyderabad",
    price: 21000,
    rating: 4.6,
    experience: "senior",
    reliabilityScore: 87,
    lat: 17.3868,
    lng: 78.4882,
  },
  {
    id: "22",
    name: "UXPulse",
    title: "UX Research Specialists",
    category: "design",
    city: "hyderabad",
    price: 9000,
    rating: 4.2,
    experience: "mid",
    reliabilityScore: 76,
    lat: 17.4,
    lng: 78.48,
  },
  {
    id: "23",
    name: "DevSprint",
    title: "Full Stack Startup Teams",
    category: "web",
    city: "hyderabad",
    price: 40000,
    rating: 4.9,
    experience: "senior",
    reliabilityScore: 94,
    lat: 17.37,
    lng: 78.5,
  },
  {
    id: "24",
    name: "DevSprint",
    title: "Startup App MVP Teams",
    category: "app",
    city: "hyderabad",
    price: 38000,
    rating: 4.8,
    experience: "senior",
    reliabilityScore: 93,
    lat: 17.3719,
    lng: 78.4986,
  },
  {
    id: "25",
    name: "PixelWave",
    title: "Creative Web Designers",
    category: "design",
    city: "hyderabad",
    price: 11000,
    rating: 4.3,
    experience: "mid",
    reliabilityScore: 81,
    lat: 17.36,
    lng: 78.47,
  },
  {
    id: "26",
    name: "AIVerse",
    title: "AI Solutions & Automation",
    category: "ai",
    city: "delhi",
    price: 50000,
    rating: 5.0,
    experience: "senior",
    reliabilityScore: 97,
    lat: 28.6139,
    lng: 77.209,
  },
  {
    id: "27",
    name: "AIVerse",
    title: "Generative AI App Builders",
    category: "ai",
    city: "delhi",
    price: 52000,
    rating: 4.9,
    experience: "senior",
    reliabilityScore: 96,
    lat: 28.6152,
    lng: 77.2113,
  },
  {
    id: "28",
    name: "GrowthHackers",
    title: "Digital Marketing Experts",
    category: "marketing",
    city: "delhi",
    price: 7000,
    rating: 4.1,
    experience: "mid",
    reliabilityScore: 74,
    lat: 28.63,
    lng: 77.22,
  },
  {
    id: "29",
    name: "GrowthHackers",
    title: "Startup Growth Campaign Managers",
    category: "marketing",
    city: "delhi",
    price: 9500,
    rating: 4.3,
    experience: "mid",
    reliabilityScore: 78,
    lat: 28.6285,
    lng: 77.2217,
  },
  {
    id: "30",
    name: "AppForge",
    title: "Flutter App Developers",
    category: "app",
    city: "delhi",
    price: 18000,
    rating: 4.6,
    experience: "mid",
    reliabilityScore: 87,
    lat: 28.62,
    lng: 77.2,
  },
  {
    id: "31",
    name: "AppForge",
    title: "Cross Platform MVP Developers",
    category: "app",
    city: "delhi",
    price: 21000,
    rating: 4.6,
    experience: "senior",
    reliabilityScore: 88,
    lat: 28.6215,
    lng: 77.2012,
  },
  {
    id: "32",
    name: "StackFusion",
    title: "MERN Stack Experts",
    category: "web",
    city: "delhi",
    price: 22000,
    rating: 4.7,
    experience: "senior",
    reliabilityScore: 90,
    lat: 28.6,
    lng: 77.23,
  },
  {
    id: "33",
    name: "StackFusion",
    title: "Backend + Frontend Product Teams",
    category: "web",
    city: "delhi",
    price: 30000,
    rating: 4.8,
    experience: "senior",
    reliabilityScore: 92,
    lat: 28.6017,
    lng: 77.2318,
  },
  {
    id: "34",
    name: "DesignHive",
    title: "Branding & UI Designers",
    category: "design",
    city: "mumbai",
    price: 14000,
    rating: 4.5,
    experience: "mid",
    reliabilityScore: 83,
    lat: 19.076,
    lng: 72.8777,
  },
  {
    id: "35",
    name: "DesignHive",
    title: "Creative Brand Designers",
    category: "design",
    city: "mumbai",
    price: 16000,
    rating: 4.6,
    experience: "senior",
    reliabilityScore: 85,
    lat: 19.0773,
    lng: 72.8756,
  },
  {
    id: "36",
    name: "CodeCrafters",
    title: "Startup Tech Teams",
    category: "web",
    city: "mumbai",
    price: 45000,
    rating: 4.8,
    experience: "senior",
    reliabilityScore: 93,
    lat: 19.09,
    lng: 72.86,
  },
  {
    id: "37",
    name: "CodeCrafters",
    title: "MVP Engineering Teams",
    category: "web",
    city: "mumbai",
    price: 42000,
    rating: 4.7,
    experience: "senior",
    reliabilityScore: 91,
    lat: 19.0918,
    lng: 72.8616,
  },
  {
    id: "38",
    name: "DevFlow",
    title: "Node.js Backend Experts",
    category: "backend",
    city: "mumbai",
    price: 16000,
    rating: 4.4,
    experience: "mid",
    reliabilityScore: 82,
    lat: 19.1,
    lng: 72.88,
  },
  {
    id: "39",
    name: "PixelGenius",
    title: "Frontend UI Developers",
    category: "web",
    city: "mumbai",
    price: 13000,
    rating: 4.3,
    experience: "junior",
    reliabilityScore: 79,
    lat: 19.07,
    lng: 72.85,
  },
  {
    id: "40",
    name: "PixelGenius",
    title: "Responsive Website Designers",
    category: "design",
    city: "mumbai",
    price: 11500,
    rating: 4.2,
    experience: "junior",
    reliabilityScore: 77,
    lat: 19.0688,
    lng: 72.8519,
  },
  {
    id: "41",
    name: "CoastCode",
    title: "React Developers for Startups",
    category: "web",
    city: "visakhapatnam",
    price: 12500,
    rating: 4.4,
    experience: "mid",
    reliabilityScore: 81,
    lat: 17.6868,
    lng: 83.2185,
  },
  {
    id: "42",
    name: "CoastCode",
    title: "API Integration Specialists",
    category: "backend",
    city: "visakhapatnam",
    price: 15500,
    rating: 4.5,
    experience: "mid",
    reliabilityScore: 83,
    lat: 17.6881,
    lng: 83.221,
  },
  {
    id: "43",
    name: "BlueHarbor Apps",
    title: "Mobile App Developers",
    category: "app",
    city: "visakhapatnam",
    price: 19000,
    rating: 4.6,
    experience: "mid",
    reliabilityScore: 86,
    lat: 17.6842,
    lng: 83.2296,
  },
  {
    id: "44",
    name: "Malabar Labs",
    title: "Web Development Experts",
    category: "web",
    city: "kochi",
    price: 14500,
    rating: 4.5,
    experience: "mid",
    reliabilityScore: 84,
    lat: 9.9312,
    lng: 76.2673,
  },
  {
    id: "45",
    name: "Malabar Labs",
    title: "UI/UX for SaaS Products",
    category: "design",
    city: "kochi",
    price: 12000,
    rating: 4.4,
    experience: "mid",
    reliabilityScore: 82,
    lat: 9.9331,
    lng: 76.2692,
  },
  {
    id: "46",
    name: "HarborStack",
    title: "DevOps & AWS Specialists",
    category: "devops",
    city: "kochi",
    price: 26000,
    rating: 4.7,
    experience: "senior",
    reliabilityScore: 89,
    lat: 9.9295,
    lng: 76.2714,
  },
  {
    id: "47",
    name: "SouthGrid",
    title: "Flutter App Developers",
    category: "app",
    city: "trivandrum",
    price: 17000,
    rating: 4.5,
    experience: "mid",
    reliabilityScore: 84,
    lat: 8.5241,
    lng: 76.9366,
  },
  {
    id: "48",
    name: "SouthGrid",
    title: "Startup Website Builders",
    category: "web",
    city: "trivandrum",
    price: 13800,
    rating: 4.4,
    experience: "mid",
    reliabilityScore: 82,
    lat: 8.526,
    lng: 76.9344,
  },
  {
    id: "49",
    name: "Kerala AI Works",
    title: "AI Automation Experts",
    category: "ai",
    city: "trivandrum",
    price: 24000,
    rating: 4.7,
    experience: "senior",
    reliabilityScore: 90,
    lat: 8.5225,
    lng: 76.9388,
  },
  {
    id: "50",
    name: "CoastalScale",
    title: "MERN Stack Developers",
    category: "web",
    city: "mangalore",
    price: 15000,
    rating: 4.4,
    experience: "mid",
    reliabilityScore: 81,
    lat: 12.9141,
    lng: 74.856,
  },
  {
    id: "51",
    name: "CoastalScale",
    title: "Node.js Backend Developers",
    category: "backend",
    city: "mangalore",
    price: 16000,
    rating: 4.5,
    experience: "mid",
    reliabilityScore: 83,
    lat: 12.9157,
    lng: 74.8581,
  },
  {
    id: "52",
    name: "Seaside Pixel",
    title: "Creative UI Designers",
    category: "design",
    city: "mangalore",
    price: 9800,
    rating: 4.3,
    experience: "junior",
    reliabilityScore: 78,
    lat: 12.9128,
    lng: 74.8542,
  },
  {
    id: "53",
    name: "PuneSprint",
    title: "Full Stack Product Developers",
    category: "web",
    city: "pune",
    price: 21000,
    rating: 4.7,
    experience: "senior",
    reliabilityScore: 89,
    lat: 18.5204,
    lng: 73.8567,
  },
  {
    id: "54",
    name: "PuneSprint",
    title: "Startup MVP Teams",
    category: "app",
    city: "pune",
    price: 32000,
    rating: 4.8,
    experience: "senior",
    reliabilityScore: 91,
    lat: 18.5222,
    lng: 73.8589,
  },
  {
    id: "55",
    name: "DataPulse",
    title: "AI/ML Product Engineers",
    category: "ai",
    city: "pune",
    price: 26000,
    rating: 4.6,
    experience: "senior",
    reliabilityScore: 88,
    lat: 18.5189,
    lng: 73.8541,
  },
  {
    id: "56",
    name: "DataPulse",
    title: "Analytics Dashboard Builders",
    category: "ai",
    city: "pune",
    price: 23000,
    rating: 4.5,
    experience: "mid",
    reliabilityScore: 86,
    lat: 18.5198,
    lng: 73.8526,
  },
];