export const offerings = [
   {
    "id": "1",
    "name": "QuickCode",
    "title": "DevOps Engineers",
    "category": "devops",
    "city": "bangalore",
    "price": 9213,
    "rating": 4.2,
    "experience": "mid",
    "reliabilityScore": 90,
    "lat": 12.9814,
    "lng": 77.6015
  },
  {
    "id": "2",
    "name": "DesignMint",
    "title": "AI Automation Experts",
    "category": "ai",
    "city": "chennai",
    "price": 12130,
    "rating": 4.1,
    "experience": "mid",
    "reliabilityScore": 80,
    "lat": 13.0969,
    "lng": 80.2671
  },
  {
    "id": "3",
    "name": "SouthGrid",
    "title": "AI Automation Experts",
    "category": "ai",
    "city": "trivandrum",
    "price": 42109,
    "rating": 4.3,
    "experience": "junior",
    "reliabilityScore": 85,
    "lat": 8.5146,
    "lng": 76.9166
  },
  {
    "id": "4",
    "name": "DevFlow",
    "title": "Backend API Developers",
    "category": "backend",
    "city": "trivandrum",
    "price": 44822,
    "rating": 4.6,
    "experience": "mid",
    "reliabilityScore": 92,
    "lat": 8.5229,
    "lng": 76.9197
  },
  {
    "id": "5",
    "name": "AlgoWorks",
    "title": "Digital Marketing Experts",
    "category": "marketing",
    "city": "mangalore",
    "price": 33304,
    "rating": 4.8,
    "experience": "mid",
    "reliabilityScore": 85,
    "lat": 12.925,
    "lng": 74.8507
  },
  {
    "id": "6",
    "name": "DesignHive",
    "title": "DevOps Engineers",
    "category": "devops",
    "city": "delhi",
    "price": 9524,
    "rating": 4.4,
    "experience": "senior",
    "reliabilityScore": 87,
    "lat": 28.59,
    "lng": 77.2088
  },
  {
    "id": "7",
    "name": "CoastCode",
    "title": "Brand Designers",
    "category": "design",
    "city": "chennai",
    "price": 14029,
    "rating": 4.2,
    "experience": "senior",
    "reliabilityScore": 94,
    "lat": 13.0721,
    "lng": 80.2703
  },
  {
    "id": "8",
    "name": "PixelGenius",
    "title": "Brand Designers",
    "category": "design",
    "city": "bangalore",
    "price": 46771,
    "rating": 4.3,
    "experience": "senior",
    "reliabilityScore": 97,
    "lat": 12.9687,
    "lng": 77.5862
  },
  {
    "id": "9",
    "name": "SouthGrid",
    "title": "Cloud Infrastructure",
    "category": "devops",
    "city": "pune",
    "price": 49069,
    "rating": 4.6,
    "experience": "senior",
    "reliabilityScore": 88,
    "lat": 18.5086,
    "lng": 73.8439
  },
  {
    "id": "10",
    "name": "SouthGrid",
    "title": "Node.js Experts",
    "category": "backend",
    "city": "kochi",
    "price": 37178,
    "rating": 4.7,
    "experience": "junior",
    "reliabilityScore": 77,
    "lat": 9.9242,
    "lng": 76.2705
  },
  {
    "id": "11",
    "name": "SouthGrid",
    "title": "Digital Marketing Experts",
    "category": "marketing",
    "city": "pune",
    "price": 26254,
    "rating": 4.7,
    "experience": "mid",
    "reliabilityScore": 87,
    "lat": 18.5236,
    "lng": 73.862
  },
  {
    "id": "12",
    "name": "DataPulse",
    "title": "Cloud Infrastructure",
    "category": "devops",
    "city": "mumbai",
    "price": 40244,
    "rating": 4.6,
    "experience": "senior",
    "reliabilityScore": 90,
    "lat": 19.08,
    "lng": 72.8699
  },
  {
    "id": "13",
    "name": "DesignMint",
    "title": "AI Engineers",
    "category": "ai",
    "city": "hyderabad",
    "price": 41577,
    "rating": 5.0,
    "experience": "mid",
    "reliabilityScore": 95,
    "lat": 17.3807,
    "lng": 78.4859
  },
  {
    "id": "14",
    "name": "DevFlow",
    "title": "Brand Designers",
    "category": "design",
    "city": "pune",
    "price": 9538,
    "rating": 4.6,
    "experience": "senior",
    "reliabilityScore": 94,
    "lat": 18.5071,
    "lng": 73.8439
  },
  {
    "id": "15",
    "name": "CoastCode",
    "title": "Backend API Developers",
    "category": "backend",
    "city": "mangalore",
    "price": 33201,
    "rating": 5.0,
    "experience": "senior",
    "reliabilityScore": 88,
    "lat": 12.8972,
    "lng": 74.853
  },
  {
    "id": "16",
    "name": "BlueHarbor",
    "title": "Microservices Developers",
    "category": "backend",
    "city": "delhi",
    "price": 16859,
    "rating": 4.9,
    "experience": "mid",
    "reliabilityScore": 92,
    "lat": 28.6105,
    "lng": 77.1945
  },
  {
    "id": "17",
    "name": "DevFlow",
    "title": "Web Development Experts",
    "category": "web",
    "city": "chennai",
    "price": 38054,
    "rating": 4.6,
    "experience": "senior",
    "reliabilityScore": 89,
    "lat": 13.0873,
    "lng": 80.2747
  },
  {
    "id": "18",
    "name": "LaunchStack",
    "title": "Web Development Experts",
    "category": "web",
    "city": "hyderabad",
    "price": 27455,
    "rating": 4.5,
    "experience": "mid",
    "reliabilityScore": 92,
    "lat": 17.3906,
    "lng": 78.4926
  },
  {
    "id": "19",
    "name": "ByteCraft",
    "title": "Digital Marketing Experts",
    "category": "marketing",
    "city": "trivandrum",
    "price": 14230,
    "rating": 4.3,
    "experience": "junior",
    "reliabilityScore": 86,
    "lat": 8.5217,
    "lng": 76.9452
  },
  {
    "id": "20",
    "name": "PixelForge",
    "title": "AWS Specialists",
    "category": "devops",
    "city": "kochi",
    "price": 18888,
    "rating": 4.2,
    "experience": "mid",
    "reliabilityScore": 85,
    "lat": 9.9325,
    "lng": 76.2655
  },
  {
    "id": "21",
    "name": "CodeCrafters",
    "title": "Flutter Developers",
    "category": "app",
    "city": "visakhapatnam",
    "price": 12874,
    "rating": 4.5,
    "experience": "senior",
    "reliabilityScore": 96,
    "lat": 17.6671,
    "lng": 83.2157
  },
  {
    "id": "22",
    "name": "AppOrbit",
    "title": "Cloud Infrastructure",
    "category": "devops",
    "city": "delhi",
    "price": 21023,
    "rating": 5.0,
    "experience": "junior",
    "reliabilityScore": 94,
    "lat": 28.5992,
    "lng": 77.1818
  },
  {
    "id": "23",
    "name": "PixelForge",
    "title": "Microservices Developers",
    "category": "backend",
    "city": "bangalore",
    "price": 21709,
    "rating": 4.2,
    "experience": "junior",
    "reliabilityScore": 82,
    "lat": 12.9814,
    "lng": 77.5957
  },
  {
    "id": "24",
    "name": "SouthGrid",
    "title": "AI Automation Experts",
    "category": "ai",
    "city": "hyderabad",
    "price": 16553,
    "rating": 4.9,
    "experience": "junior",
    "reliabilityScore": 88,
    "lat": 17.3684,
    "lng": 78.4644
  },
  {
    "id": "25",
    "name": "DevFlow",
    "title": "Mobile App Developers",
    "category": "app",
    "city": "delhi",
    "price": 9914,
    "rating": 4.8,
    "experience": "mid",
    "reliabilityScore": 75,
    "lat": 28.6256,
    "lng": 77.2186
  },
  {
    "id": "26",
    "name": "LaunchStack",
    "title": "AI Engineers",
    "category": "ai",
    "city": "mumbai",
    "price": 49421,
    "rating": 5.0,
    "experience": "junior",
    "reliabilityScore": 78,
    "lat": 19.0763,
    "lng": 72.8724
  },
  {
    "id": "27",
    "name": "UIHive",
    "title": "Flutter Developers",
    "category": "app",
    "city": "chennai",
    "price": 26541,
    "rating": 4.2,
    "experience": "junior",
    "reliabilityScore": 88,
    "lat": 13.0822,
    "lng": 80.2709
  },
  {
    "id": "28",
    "name": "CoastCode",
    "title": "Microservices Developers",
    "category": "backend",
    "city": "trivandrum",
    "price": 16279,
    "rating": 4.7,
    "experience": "senior",
    "reliabilityScore": 86,
    "lat": 8.5122,
    "lng": 76.9376
  },
  {
    "id": "29",
    "name": "DevSprint",
    "title": "Microservices Developers",
    "category": "backend",
    "city": "mumbai",
    "price": 10992,
    "rating": 4.7,
    "experience": "junior",
    "reliabilityScore": 81,
    "lat": 19.0842,
    "lng": 72.8661
  },
  {
    "id": "30",
    "name": "CodeNest",
    "title": "Cross Platform Apps",
    "category": "app",
    "city": "bangalore",
    "price": 49053,
    "rating": 5.0,
    "experience": "senior",
    "reliabilityScore": 84,
    "lat": 12.9883,
    "lng": 77.5998
  },
  {
    "id": "31",
    "name": "StackFusion",
    "title": "Flutter Developers",
    "category": "app",
    "city": "trivandrum",
    "price": 16212,
    "rating": 5.0,
    "experience": "mid",
    "reliabilityScore": 91,
    "lat": 8.5333,
    "lng": 76.9221
  },
  {
    "id": "32",
    "name": "CodeNest",
    "title": "Cross Platform Apps",
    "category": "app",
    "city": "bangalore",
    "price": 40359,
    "rating": 4.9,
    "experience": "mid",
    "reliabilityScore": 80,
    "lat": 12.9718,
    "lng": 77.5977
  },
  {
    "id": "33",
    "name": "UIHive",
    "title": "DevOps Engineers",
    "category": "devops",
    "city": "delhi",
    "price": 44188,
    "rating": 4.3,
    "experience": "junior",
    "reliabilityScore": 76,
    "lat": 28.5912,
    "lng": 77.1804
  },
  {
    "id": "34",
    "name": "MalabarLabs",
    "title": "Microservices Developers",
    "category": "backend",
    "city": "delhi",
    "price": 8736,
    "rating": 4.3,
    "experience": "mid",
    "reliabilityScore": 79,
    "lat": 28.6217,
    "lng": 77.1852
  },
  {
    "id": "35",
    "name": "QuickCode",
    "title": "Frontend Developers",
    "category": "web",
    "city": "hyderabad",
    "price": 34809,
    "rating": 4.8,
    "experience": "senior",
    "reliabilityScore": 95,
    "lat": 17.3997,
    "lng": 78.4756
  },
  {
    "id": "36",
    "name": "LaunchStack",
    "title": "ML Engineers",
    "category": "ai",
    "city": "visakhapatnam",
    "price": 48323,
    "rating": 4.5,
    "experience": "senior",
    "reliabilityScore": 97,
    "lat": 17.6995,
    "lng": 83.211
  },
  {
    "id": "37",
    "name": "AIVerse",
    "title": "Growth Managers",
    "category": "marketing",
    "city": "mumbai",
    "price": 36620,
    "rating": 4.2,
    "experience": "mid",
    "reliabilityScore": 94,
    "lat": 19.0577,
    "lng": 72.8892
  },
  {
    "id": "38",
    "name": "DesignHive",
    "title": "AWS Specialists",
    "category": "devops",
    "city": "hyderabad",
    "price": 27611,
    "rating": 4.8,
    "experience": "mid",
    "reliabilityScore": 88,
    "lat": 17.3991,
    "lng": 78.4683
  },
  {
    "id": "39",
    "name": "UIHive",
    "title": "MERN Stack Developers",
    "category": "web",
    "city": "trivandrum",
    "price": 14008,
    "rating": 4.3,
    "experience": "mid",
    "reliabilityScore": 79,
    "lat": 8.5361,
    "lng": 76.9495
  },
  {
    "id": "40",
    "name": "LaunchStack",
    "title": "Frontend Developers",
    "category": "web",
    "city": "trivandrum",
    "price": 21354,
    "rating": 4.3,
    "experience": "senior",
    "reliabilityScore": 93,
    "lat": 8.5313,
    "lng": 76.9318
  },
  {
    "id": "41",
    "name": "CoastCode",
    "title": "Backend API Developers",
    "category": "backend",
    "city": "kochi",
    "price": 13093,
    "rating": 4.7,
    "experience": "mid",
    "reliabilityScore": 91,
    "lat": 9.9215,
    "lng": 76.268
  },
  {
    "id": "42",
    "name": "MalabarLabs",
    "title": "Microservices Developers",
    "category": "backend",
    "city": "bangalore",
    "price": 29647,
    "rating": 4.3,
    "experience": "mid",
    "reliabilityScore": 78,
    "lat": 12.9631,
    "lng": 77.576
  },
  {
    "id": "43",
    "name": "AIVerse",
    "title": "Cross Platform Apps",
    "category": "app",
    "city": "delhi",
    "price": 24899,
    "rating": 4.7,
    "experience": "senior",
    "reliabilityScore": 85,
    "lat": 28.6157,
    "lng": 77.1888
  },
  {
    "id": "44",
    "name": "AIVerse",
    "title": "ML Engineers",
    "category": "ai",
    "city": "hyderabad",
    "price": 19433,
    "rating": 4.8,
    "experience": "mid",
    "reliabilityScore": 83,
    "lat": 17.3742,
    "lng": 78.4886
  },
  {
    "id": "45",
    "name": "CoastCode",
    "title": "Cloud Infrastructure",
    "category": "devops",
    "city": "mumbai",
    "price": 17729,
    "rating": 4.2,
    "experience": "senior",
    "reliabilityScore": 96,
    "lat": 19.0528,
    "lng": 72.866
  },
  {
    "id": "46",
    "name": "DataPulse",
    "title": "Frontend Developers",
    "category": "web",
    "city": "delhi",
    "price": 45348,
    "rating": 4.5,
    "experience": "mid",
    "reliabilityScore": 76,
    "lat": 28.6014,
    "lng": 77.2064
  },
  {
    "id": "47",
    "name": "CloudBridge",
    "title": "AI Automation Experts",
    "category": "ai",
    "city": "trivandrum",
    "price": 24692,
    "rating": 4.8,
    "experience": "mid",
    "reliabilityScore": 76,
    "lat": 8.5288,
    "lng": 76.9484
  },
  {
    "id": "48",
    "name": "MalabarLabs",
    "title": "Growth Managers",
    "category": "marketing",
    "city": "mangalore",
    "price": 43754,
    "rating": 4.3,
    "experience": "senior",
    "reliabilityScore": 85,
    "lat": 12.9053,
    "lng": 74.851
  },
  {
    "id": "49",
    "name": "CoastCode",
    "title": "ML Engineers",
    "category": "ai",
    "city": "trivandrum",
    "price": 27146,
    "rating": 4.3,
    "experience": "junior",
    "reliabilityScore": 77,
    "lat": 8.5338,
    "lng": 76.9457
  },
  {
    "id": "50",
    "name": "CodeCrafters",
    "title": "Web Development Experts",
    "category": "web",
    "city": "trivandrum",
    "price": 18062,
    "rating": 4.8,
    "experience": "mid",
    "reliabilityScore": 96,
    "lat": 8.5352,
    "lng": 76.9429
  },
  {
    "id": "51",
    "name": "QuickCode",
    "title": "AWS Specialists",
    "category": "devops",
    "city": "mumbai",
    "price": 11628,
    "rating": 4.8,
    "experience": "junior",
    "reliabilityScore": 78,
    "lat": 19.0681,
    "lng": 72.8784
  },
  {
    "id": "52",
    "name": "BlueHarbor",
    "title": "Brand Designers",
    "category": "design",
    "city": "kochi",
    "price": 17541,
    "rating": 4.8,
    "experience": "junior",
    "reliabilityScore": 75,
    "lat": 9.9206,
    "lng": 76.2625
  },
  {
    "id": "53",
    "name": "DevFlow",
    "title": "Brand Designers",
    "category": "design",
    "city": "trivandrum",
    "price": 23567,
    "rating": 4.3,
    "experience": "mid",
    "reliabilityScore": 92,
    "lat": 8.5014,
    "lng": 76.9478
  },
  {
    "id": "54",
    "name": "UIHive",
    "title": "Digital Marketing Experts",
    "category": "marketing",
    "city": "visakhapatnam",
    "price": 40368,
    "rating": 4.8,
    "experience": "mid",
    "reliabilityScore": 75,
    "lat": 17.6669,
    "lng": 83.2092
  },
  {
    "id": "55",
    "name": "CloudBridge",
    "title": "Flutter Developers",
    "category": "app",
    "city": "bangalore",
    "price": 49048,
    "rating": 4.7,
    "experience": "mid",
    "reliabilityScore": 83,
    "lat": 12.9603,
    "lng": 77.5744
  },
  {
    "id": "56",
    "name": "CloudBridge",
    "title": "Mobile App Developers",
    "category": "app",
    "city": "mangalore",
    "price": 38448,
    "rating": 4.6,
    "experience": "senior",
    "reliabilityScore": 96,
    "lat": 12.9195,
    "lng": 74.8522
  },
  {
    "id": "57",
    "name": "DataPulse",
    "title": "Product Designers",
    "category": "design",
    "city": "hyderabad",
    "price": 31823,
    "rating": 4.2,
    "experience": "junior",
    "reliabilityScore": 92,
    "lat": 17.3821,
    "lng": 78.4606
  },
  {
    "id": "58",
    "name": "DesignMint",
    "title": "Cloud Infrastructure",
    "category": "devops",
    "city": "bangalore",
    "price": 31441,
    "rating": 4.2,
    "experience": "mid",
    "reliabilityScore": 79,
    "lat": 12.9747,
    "lng": 77.6074
  },
  {
    "id": "59",
    "name": "MalabarLabs",
    "title": "ML Engineers",
    "category": "ai",
    "city": "mumbai",
    "price": 18936,
    "rating": 4.6,
    "experience": "mid",
    "reliabilityScore": 75,
    "lat": 19.0809,
    "lng": 72.885
  },
  {
    "id": "60",
    "name": "SouthGrid",
    "title": "Backend API Developers",
    "category": "backend",
    "city": "delhi",
    "price": 26440,
    "rating": 4.4,
    "experience": "mid",
    "reliabilityScore": 90,
    "lat": 28.597,
    "lng": 77.2006
  },
  {
    "id": "61",
    "name": "UIHive",
    "title": "AI Automation Experts",
    "category": "ai",
    "city": "mangalore",
    "price": 38943,
    "rating": 4.2,
    "experience": "mid",
    "reliabilityScore": 83,
    "lat": 12.8987,
    "lng": 74.8438
  },
  {
    "id": "62",
    "name": "PixelForge",
    "title": "Flutter Developers",
    "category": "app",
    "city": "trivandrum",
    "price": 18973,
    "rating": 4.7,
    "experience": "junior",
    "reliabilityScore": 82,
    "lat": 8.508,
    "lng": 76.9119
  },
  {
    "id": "63",
    "name": "CodeNest",
    "title": "Mobile App Developers",
    "category": "app",
    "city": "pune",
    "price": 34316,
    "rating": 4.6,
    "experience": "junior",
    "reliabilityScore": 95,
    "lat": 18.5374,
    "lng": 73.8635
  },
  {
    "id": "64",
    "name": "CoastCode",
    "title": "DevOps Engineers",
    "category": "devops",
    "city": "bangalore",
    "price": 18308,
    "rating": 4.5,
    "experience": "senior",
    "reliabilityScore": 81,
    "lat": 12.9834,
    "lng": 77.6065
  },
  {
    "id": "65",
    "name": "ByteCraft",
    "title": "AI Automation Experts",
    "category": "ai",
    "city": "mumbai",
    "price": 26016,
    "rating": 4.7,
    "experience": "junior",
    "reliabilityScore": 92,
    "lat": 19.0865,
    "lng": 72.857
  },
  {
    "id": "66",
    "name": "AIVerse",
    "title": "Growth Managers",
    "category": "marketing",
    "city": "mangalore",
    "price": 37606,
    "rating": 4.5,
    "experience": "senior",
    "reliabilityScore": 83,
    "lat": 12.8987,
    "lng": 74.8437
  },
  {
    "id": "67",
    "name": "UIHive",
    "title": "UI/UX Designers",
    "category": "design",
    "city": "mangalore",
    "price": 29833,
    "rating": 4.4,
    "experience": "junior",
    "reliabilityScore": 87,
    "lat": 12.902,
    "lng": 74.8314
  },
  {
    "id": "68",
    "name": "CodeCrafters",
    "title": "AI Engineers",
    "category": "ai",
    "city": "chennai",
    "price": 15306,
    "rating": 4.8,
    "experience": "junior",
    "reliabilityScore": 93,
    "lat": 13.0809,
    "lng": 80.2525
  },
  {
    "id": "69",
    "name": "CloudBridge",
    "title": "Web Development Experts",
    "category": "web",
    "city": "hyderabad",
    "price": 44741,
    "rating": 4.9,
    "experience": "mid",
    "reliabilityScore": 78,
    "lat": 17.387,
    "lng": 78.4731
  },
  {
    "id": "70",
    "name": "CoastCode",
    "title": "Growth Managers",
    "category": "marketing",
    "city": "kochi",
    "price": 25215,
    "rating": 4.9,
    "experience": "senior",
    "reliabilityScore": 93,
    "lat": 9.9377,
    "lng": 76.2547
  },
  {
    "id": "71",
    "name": "DevFlow",
    "title": "AI Engineers",
    "category": "ai",
    "city": "visakhapatnam",
    "price": 18149,
    "rating": 4.7,
    "experience": "junior",
    "reliabilityScore": 91,
    "lat": 17.6769,
    "lng": 83.1959
  },
  {
    "id": "72",
    "name": "DesignMint",
    "title": "Cloud Infrastructure",
    "category": "devops",
    "city": "visakhapatnam",
    "price": 33191,
    "rating": 4.2,
    "experience": "senior",
    "reliabilityScore": 95,
    "lat": 17.6979,
    "lng": 83.201
  },
  {
    "id": "73",
    "name": "DevFlow",
    "title": "Microservices Developers",
    "category": "backend",
    "city": "trivandrum",
    "price": 13654,
    "rating": 4.1,
    "experience": "senior",
    "reliabilityScore": 89,
    "lat": 8.5152,
    "lng": 76.9436
  },
  {
    "id": "74",
    "name": "LaunchStack",
    "title": "ML Engineers",
    "category": "ai",
    "city": "visakhapatnam",
    "price": 30484,
    "rating": 4.4,
    "experience": "mid",
    "reliabilityScore": 96,
    "lat": 17.6623,
    "lng": 83.194
  },
  {
    "id": "75",
    "name": "UIHive",
    "title": "Web Development Experts",
    "category": "web",
    "city": "chennai",
    "price": 11463,
    "rating": 4.2,
    "experience": "junior",
    "reliabilityScore": 96,
    "lat": 13.0745,
    "lng": 80.2648
  },
  {
    "id": "76",
    "name": "LaunchStack",
    "title": "Web Development Experts",
    "category": "web",
    "city": "hyderabad",
    "price": 14585,
    "rating": 4.8,
    "experience": "senior",
    "reliabilityScore": 86,
    "lat": 17.384,
    "lng": 78.4756
  },
  {
    "id": "77",
    "name": "DesignHive",
    "title": "Growth Managers",
    "category": "marketing",
    "city": "visakhapatnam",
    "price": 49945,
    "rating": 4.2,
    "experience": "senior",
    "reliabilityScore": 95,
    "lat": 17.6688,
    "lng": 83.2238
  },
  {
    "id": "78",
    "name": "CodeCrafters",
    "title": "MERN Stack Developers",
    "category": "web",
    "city": "pune",
    "price": 28132,
    "rating": 4.9,
    "experience": "mid",
    "reliabilityScore": 82,
    "lat": 18.5047,
    "lng": 73.8384
  },
  {
    "id": "79",
    "name": "CodeCrafters",
    "title": "Frontend Developers",
    "category": "web",
    "city": "pune",
    "price": 13996,
    "rating": 4.4,
    "experience": "senior",
    "reliabilityScore": 76,
    "lat": 18.5157,
    "lng": 73.8498
  },
  {
    "id": "80",
    "name": "AIVerse",
    "title": "Brand Designers",
    "category": "design",
    "city": "mangalore",
    "price": 13424,
    "rating": 4.2,
    "experience": "mid",
    "reliabilityScore": 97,
    "lat": 12.911,
    "lng": 74.8439
  },
  {
    "id": "81",
    "name": "SouthGrid",
    "title": "Mobile App Developers",
    "category": "app",
    "city": "visakhapatnam",
    "price": 21891,
    "rating": 4.9,
    "experience": "mid",
    "reliabilityScore": 91,
    "lat": 17.6947,
    "lng": 83.1988
  },
  {
    "id": "82",
    "name": "UIHive",
    "title": "Backend API Developers",
    "category": "backend",
    "city": "delhi",
    "price": 17501,
    "rating": 4.9,
    "experience": "senior",
    "reliabilityScore": 90,
    "lat": 28.6033,
    "lng": 77.1936
  },
  {
    "id": "83",
    "name": "DesignHive",
    "title": "AWS Specialists",
    "category": "devops",
    "city": "pune",
    "price": 45665,
    "rating": 5.0,
    "experience": "senior",
    "reliabilityScore": 79,
    "lat": 18.5076,
    "lng": 73.8697
  },
  {
    "id": "84",
    "name": "CloudBridge",
    "title": "UI/UX Designers",
    "category": "design",
    "city": "chennai",
    "price": 30954,
    "rating": 4.5,
    "experience": "senior",
    "reliabilityScore": 84,
    "lat": 13.0679,
    "lng": 80.2629
  },
  {
    "id": "85",
    "name": "ByteCraft",
    "title": "Cross Platform Apps",
    "category": "app",
    "city": "pune",
    "price": 48609,
    "rating": 4.5,
    "experience": "junior",
    "reliabilityScore": 79,
    "lat": 18.5206,
    "lng": 73.8369
  },
  {
    "id": "86",
    "name": "DevFlow",
    "title": "Digital Marketing Experts",
    "category": "marketing",
    "city": "trivandrum",
    "price": 39981,
    "rating": 4.8,
    "experience": "junior",
    "reliabilityScore": 79,
    "lat": 8.5155,
    "lng": 76.9401
  },
  {
    "id": "87",
    "name": "UIHive",
    "title": "UI/UX Designers",
    "category": "design",
    "city": "trivandrum",
    "price": 30912,
    "rating": 4.5,
    "experience": "mid",
    "reliabilityScore": 95,
    "lat": 8.5159,
    "lng": 76.9474
  },
  {
    "id": "88",
    "name": "CodeNest",
    "title": "MERN Stack Developers",
    "category": "web",
    "city": "visakhapatnam",
    "price": 39726,
    "rating": 4.9,
    "experience": "senior",
    "reliabilityScore": 95,
    "lat": 17.6638,
    "lng": 83.2173
  },
  {
    "id": "89",
    "name": "AppOrbit",
    "title": "UI/UX Designers",
    "category": "design",
    "city": "delhi",
    "price": 34460,
    "rating": 4.1,
    "experience": "mid",
    "reliabilityScore": 85,
    "lat": 28.6105,
    "lng": 77.1974
  },
  {
    "id": "90",
    "name": "DataPulse",
    "title": "AI Engineers",
    "category": "ai",
    "city": "visakhapatnam",
    "price": 20219,
    "rating": 5.0,
    "experience": "senior",
    "reliabilityScore": 91,
    "lat": 17.6953,
    "lng": 83.215
  },
  {
    "id": "91",
    "name": "DataPulse",
    "title": "AI Engineers",
    "category": "ai",
    "city": "mangalore",
    "price": 28816,
    "rating": 4.9,
    "experience": "junior",
    "reliabilityScore": 93,
    "lat": 12.8907,
    "lng": 74.8576
  },
  {
    "id": "92",
    "name": "UIHive",
    "title": "Cloud Infrastructure",
    "category": "devops",
    "city": "mumbai",
    "price": 9539,
    "rating": 4.9,
    "experience": "mid",
    "reliabilityScore": 78,
    "lat": 19.079,
    "lng": 72.8639
  },
  {
    "id": "93",
    "name": "LaunchStack",
    "title": "Backend API Developers",
    "category": "backend",
    "city": "bangalore",
    "price": 9603,
    "rating": 4.2,
    "experience": "junior",
    "reliabilityScore": 81,
    "lat": 12.9792,
    "lng": 77.6078
  },
  {
    "id": "94",
    "name": "AppOrbit",
    "title": "Backend API Developers",
    "category": "backend",
    "city": "mumbai",
    "price": 43072,
    "rating": 4.1,
    "experience": "senior",
    "reliabilityScore": 83,
    "lat": 19.0703,
    "lng": 72.8857
  },
  {
    "id": "95",
    "name": "StackFusion",
    "title": "Digital Marketing Experts",
    "category": "marketing",
    "city": "hyderabad",
    "price": 12854,
    "rating": 4.7,
    "experience": "senior",
    "reliabilityScore": 96,
    "lat": 17.3687,
    "lng": 78.4856
  },
  {
    "id": "96",
    "name": "AIVerse",
    "title": "Digital Marketing Experts",
    "category": "marketing",
    "city": "visakhapatnam",
    "price": 44175,
    "rating": 4.7,
    "experience": "junior",
    "reliabilityScore": 78,
    "lat": 17.6918,
    "lng": 83.2127
  },
  {
    "id": "97",
    "name": "AlgoWorks",
    "title": "Growth Managers",
    "category": "marketing",
    "city": "hyderabad",
    "price": 47780,
    "rating": 4.9,
    "experience": "junior",
    "reliabilityScore": 83,
    "lat": 17.3625,
    "lng": 78.4884
  },
  {
    "id": "98",
    "name": "BlueHarbor",
    "title": "Mobile App Developers",
    "category": "app",
    "city": "delhi",
    "price": 40390,
    "rating": 4.5,
    "experience": "senior",
    "reliabilityScore": 88,
    "lat": 28.6052,
    "lng": 77.2005
  },
  {
    "id": "99",
    "name": "AIVerse",
    "title": "Mobile App Developers",
    "category": "app",
    "city": "visakhapatnam",
    "price": 42062,
    "rating": 4.3,
    "experience": "senior",
    "reliabilityScore": 96,
    "lat": 17.6717,
    "lng": 83.2258
  },
  {
    "id": "100",
    "name": "LaunchStack",
    "title": "Cross Platform Apps",
    "category": "app",
    "city": "mangalore",
    "price": 15236,
    "rating": 4.8,
    "experience": "senior",
    "reliabilityScore": 87,
    "lat": 12.9127,
    "lng": 74.8387
  },
];